using System;
using System.Configuration;

namespace Isidos.Paysera
{
    /// <summary>
    /// This class was generated by the AppSettings T4 template
    /// </summary>
    public static class AppSettings
    {
        public static string PayseraPublicKeyUrl { get { return GetConfigSettingItem("PayseraPublicKeyUrl"); } }
        public static string Version { get { return GetConfigSettingItem("Version"); } }
        public static string PayUrl { get { return GetConfigSettingItem("PayUrl"); } }
        public static string PayseraDateFormat { get { return GetConfigSettingItem("PayseraDateFormat"); } }
        public static string ProjectId { get { return GetConfigSettingItem("ProjectId"); } }
        public static string SignPassword { get { return GetConfigSettingItem("SignPassword"); } }
        public static string AcceptUrl { get { return GetConfigSettingItem("AcceptUrl"); } }
        public static string CancelUrl { get { return GetConfigSettingItem("CancelUrl"); } }
        public static string CallbackUrl { get { return GetConfigSettingItem("CallbackUrl"); } }
    
        private const string MISSING_CONFIG = "Invalid configuration. Required AppSettings section is missing";
        private const string INVALID_CONFIG_SETTING = "Invalid configuration setting name: {0}";

        private static string GetConfigSettingItem(string name)
        {
            if (ConfigurationManager.AppSettings == null)
                throw new ConfigurationErrorsException(MISSING_CONFIG);

            string value = null;
            if (ConfigurationManager.AppSettings.Count != 0)
            {
                try
                {
                    value = ConfigurationManager.AppSettings.Get(name);
                }
                catch (Exception exception)
                {
                    throw new ConfigurationErrorsException(SettingItemErrorMessage(name, exception));
                }
            }
            // Older versions of the NETFx doesn't have IsNullOrWhiteSpace
            if (string.IsNullOrEmpty(value))
            {
			//    throw new ConfigurationErrorsException(SettingItemErrorMessage(name));
				return string.Empty;
			}
            return value;
        }
        
        private static string SettingItemErrorMessage(string name)
        {
            return string.Format(INVALID_CONFIG_SETTING, name);
        }

        private static string SettingItemErrorMessage(string name, Exception exception)
        {
            return string.Format(INVALID_CONFIG_SETTING, name) + exception.Message;
        }
    }
}
